#!/bin/bash

if [[ $# -eq 0 ]]; then
    echo "Usage: . ./daosenv <root_project_directory>"
    return 1
fi

DAOS_HOME=$1

if [[ ! -d "$DAOS_HOME" ]]; then
    echo "Error: Directory $DAOS_HOME does not exist."
    return 1
fi

USER=$(whoami)
GROUP=$(id -gn)
ALIAS_FILE="$DAOS_HOME/aliases"
DAOS_INSTALL_DIR="$DAOS_HOME/build/daos/install"

BIN_DIR="$DAOS_INSTALL_DIR/bin"
LIB_DIR="$DAOS_INSTALL_DIR/lib"
LIB64_DIR="$DAOS_INSTALL_DIR/lib64"

export DAOS_INSTALL_PATH=$DAOS_INSTALL_DIR

if [[ -d "$BIN_DIR" ]]; then
    export PATH="$BIN_DIR:$PATH"
    echo "Added $BIN_DIR to PATH"
fi

if [[ -d "$LIB_DIR" ]]; then
    export LD_LIBRARY_PATH="$LIB_DIR:$LD_LIBRARY_PATH"
    echo "Added $LIB_DIR to LD_LIBRARY_PATH"
fi

if [[ -d "$LIB64_DIR" ]]; then
    export LD_LIBRARY_PATH="$LIB64_DIR:$LD_LIBRARY_PATH"
    echo "Added $LIB64_DIR to LD_LIBRARY_PATH"
fi

echo "Current PATH: $PATH"
echo "Current LD_LIBRARY_PATH: $LD_LIBRARY_PATH"

# Set aliases
if [[ -f "$ALIAS_FILE" ]]; then
    source "$ALIAS_FILE"
    echo "Aliases loaded from $ALIAS_FILE"
else
    echo "Alias file $ALIAS_FILE not found"
fi

# Update Systemd Service Profile
DAOS_SERVER_TEMPLATE_FILE="$DAOS_HOME/systemd/daos_server.service.template"
DAOS_SERVER_SERVICE_FILE="$DAOS_HOME/systemd/daos_server.service"
DAOS_AGENT_TEMPLATE_FILE="$DAOS_HOME/systemd/daos_agent.service.template"
DAOS_AGENT_SERVICE_FILE="$DAOS_HOME/systemd/daos_agent.service"

# Sub
sed -e "s|\${USER}|$USER|g" \
    -e "s|\${GROUP}|$GROUP|g" \
    -e "s|\${DAOS_ENV_PATH}|$DAOS_HOME|g" \
    "$DAOS_SERVER_TEMPLATE_FILE" > "$DAOS_SERVER_SERVICE_FILE"
sed -e "s|\${USER}|$USER|g" \
    -e "s|\${GROUP}|$GROUP|g" \
    -e "s|\${DAOS_ENV_PATH}|$DAOS_HOME|g" \
    "$DAOS_AGENT_TEMPLATE_FILE" > "$DAOS_AGENT_SERVICE_FILE"

chmod 644 "$DAOS_SERVER_SERVICE_FILE"
chmod 644 "$DAOS_AGENT_SERVICE_FILE"

mkdir -p /var/run/daos_server
mkdir -p /var/run/daos_agent

sysctl -w vm.nr_hugepages=4096
cat /proc/meminfo | grep HugePages
